name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-using-java-8:
    name: 'Test using Java 8'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Print java version
      run: java -version

    - name: Install dependencies
      run: lein deps

    - name: Run clj tests
      run: lein test

  test-using-java-11:
    name: 'Test using Java 11'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Print java version
      run: java -version

    - name: Install dependencies
      run: lein deps

    - name: Run clj tests
      run: lein test

  test-using-java-17:
    name: 'Test using Java 17'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Print java version
      run: java -version

    - name: Install dependencies
      run: lein deps

    - name: Run clj tests
      run: lein test

  test-using-java-21:
    name: 'Test using Java 21'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 21

    - name: Print java version
      run: java -version

    - name: Install dependencies
      run: lein deps

    - name: Run clj tests
      run: lein test

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Lint check
      run: lein lint
